- charts/dex/Chart.yaml
- charts/dex/templates/deployment.yaml
> Add missing envFrom to the deployment

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/ci/pod-annotations-values.yaml
- charts/dex/templates/deployment.yaml
> fix(charts/dex): fix template rendering when podAnnotations is set

- .github/workflows/ci.yaml
Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>
> ci: add check for docs

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/deployment.yaml
- charts/dex/templates/service.yaml
- charts/dex/values.yaml
> Add HTTPS support

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/ingress.yaml
- charts/dex/values.yaml
Reverting this change until the helm template lands on a final version.
See helm/helm#9585
> Revert breaking change

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/ingress.yaml
> Fix ingress

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/values.yaml
> Fix missing https port

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/deployment.yaml
- charts/dex/values.yaml
> Priority class

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/ci/no-config-secret.yaml
- charts/dex/templates/deployment.yaml
- charts/dex/templates/tests/no-config-secret.yaml
> Add ability to override `checksum/config` annotation

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/service.yaml
- charts/dex/values.yaml
> Allow to provide a clusterIP for the service

- charts/dex/Chart.yaml
- charts/dex/README.md
Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>
> Fix artifacthub annotation

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/deployment.yaml
- charts/dex/values.yaml
The PR adds the ability to configure environment variables that reference `Secrets` or `ConfigMaps`.
See #53 for more information.
Fixes #53
> Add support for secret referencing on environment variables

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/servicemonitor.yaml
- charts/dex/values.yaml
Add ServiceMonitor to the Dex chart
Replaces #69
> Service monitor

- charts/dex/Chart.yaml
- charts/dex/README.md
Update Dex.
Update Dex to the latest version.
> Update Dex to v2.35.0

- charts/dex/Chart.yaml
- charts/dex/README.md
Update Dex.
Update Dex to the latest version.
> Upgrade dex

- README.md
Fix https://github.com/badges/shields/issues/8671
> Update GitHub workflow status

- charts/dex/README.md
> fix typo in README.md

- charts/dex/Chart.yaml
- charts/dex/README.md
> feat: upgrade Dex to 2.38.0

- charts/dex/Chart.yaml
- charts/dex/README.md
https://github.com/dexidp/dex/releases/tag/v2.39.1
> Bump Dex to v2.39.1

- charts/dex/Chart.yaml
- charts/dex/README.md
https://github.com/dexidp/dex/releases/tag/v2.40.0
> Bump Dex to v2.40.0

- charts/dex/Chart.yaml
- charts/dex/README.md
https://github.com/dexidp/dex/releases/tag/v2.41.0
> Bump Dex to v2.41.0

- charts/dex/Chart.yaml
- charts/dex/README.md
https://github.com/dexidp/dex/releases/tag/v2.41.1
> Bump Dex to v2.41.1

- charts/dex/Chart.yaml
- charts/dex/README.md
- charts/dex/templates/_helpers.tpl
Fix invalid service monitor namespace
Fixes #148
> fix: service monitor namespace

- charts/dex/Chart.yaml
- charts/dex/README.md
> chore: update Dex to 2.42.0
