dexidp/helm-charts

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/ingress.yaml
charts/dex/values.yaml

This PR extends the charts with the possibility of using ingressClassName for ingress resources instead the deprecated ingress.classname annotation.

ingressClass support

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/_helpers.tpl
charts/dex/templates/deployment.yaml
charts/dex/templates/secret.yaml

Remove the old component name. It was only added to support multiple secrets (eg. for env vars), but it's not needed anymore.

Use full name as secret name

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/ci/config-secret-values.yaml
charts/dex/templates/_helpers.tpl
charts/dex/templates/deployment.yaml
charts/dex/templates/secret.yaml
charts/dex/values.yaml

This PR adds external secret support.
This is useful to let the end user bring his own configuration from an existing secret.

feat: add external secret support

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/deployment.yaml
charts/dex/values.yaml

I'd like to connect to a LDAPS Server by a hostname which is not registered in cluster dns. Otherwise, the SNI in the tls cert won't match.

add support for hostAliases

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/deployment.yaml
charts/dex/values.yaml

Add `strategy` field in value in order to override the `strategy` field from Dex deployment
Fixes: #66

Add strategy for dex deployment

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/deployment.yaml
charts/dex/values.yaml

Added support for pod topologySpreadConstraints in deployment spec
We use topologySpreadConstraints as a better alternative for podAnityAffinity. Also some projects as https://github.com/aws/karpenter currently doesn't support podAnityAffinity

Add support for pod topologySpreadConstraints in deployment spec

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/deployment.yaml

In chart version 0.6.6 (#71), the template rendering broke because it tries to use `.Values.topologySpreadConstraints` while still within the `.Values.affinity` scope. This lead to an error like the following:
```
Error: template: dex/templates/deployment.yaml:126:22: executing "dex/templates/deployment.yaml" at <.Values.topologySpreadConstraints>: nil pointer evaluating interface {}.topologySpreadConstraints
```
Moves the rendering of `topologySpreadConstraints` outside the scope of the `.Values.affinity` block.

fix(charts/dex): fix render error caused by #71

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/rbac.yaml

If you choose to use a `ClusterRole` with `rbac.createClusterScoped: true` (the [default](https://github.com/dexidp/helm-charts/blob/5d4f5f4c1b05412bc88ddec868185a81ecee3926/charts/dex/values.yaml#L104)), using a [`RoleBinding`](https://github.com/dexidp/helm-charts/blob/5d4f5f4c1b05412bc88ddec868185a81ecee3926/charts/dex/templates/rbac.yaml#L41) and not a `ClusterRoleBinding` results in the controller not having permission to list and create the Dex CRD's.
* Resolves #79
* Reverts to using `ClusterRoleBinding` for `{{ include "dex.fullname" . }}-cluster` (fixes controller permissions when creating the CRD's)
* Adds `list` verb to `ClusterRole` for `{{ include "dex.fullname" . }}` (fixes permissions whe controller tries to list custom resources)

Use ClusterRoleBinding for ClusterRole and allow 'list' for CRD's

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/servicemonitor.yaml

Correct indentation for `ServiceMonitor` when using `serviceMonitor.labels`
If `serviceMonitor.labels` is specified, invalid YAML is generated in `ServiceMonitor`
This fixes only that.

Fix indentation for ServiceMonitor when using serviceMonitor.labels

---

charts/dex/Chart.yaml
charts/dex/README.md

New release - https://github.com/dexidp/dex/releases/tag/v2.34.0

Bump Dex to v2.34.0

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/networkpolicy.yaml
charts/dex/values.yaml

Add the ability to create a network policy with customizable egress
Network policies are a best practice.
Specifically when deploying in a NS already containing network policies, it is required.
N/A

Add NetworkPolicy

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/_helpers.tpl
charts/dex/values.yaml

Usefull when we have a policies manager as Kyverno.
Signed-off-by: Flaagada <mary.thibault2@gmail.com>
Support a common labels for all resources.
When we used a policies manager as Kyverno, it's usefull to be able to add a common labels on all resources created by the chart in order to respect the policy.

Add: support common labels for all resources

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/ingress.yaml

Hi, I would like to use dex as part of a umbrella helm chart. For the user experience, there is currently global (sub)domain configuration across all helm charts and sub-charts are able to use the helm evaluation function to build a hostname. After merging the PR, I could use somelike like this in my value yaml
```yaml
dex:
ingress:
annotations:
cert-manager.io/cluster-issuer: letsencrypt
hosts:
- host: 'auth.{{ $.Values.global.domain }}'
paths:
- path: /
pathType: Prefix
tls:
- secretName: tls-secret-dex
hosts:
- 'auth.{{ $.Values.global.domain }}'
```
And user only needs to define `--set global.domain=example.com`.
Note, w/o this, end users needs to pass the whole list item, since helm is not able to merge lists.
[kube-prometheus-stack](https://github.com/prometheus-community/helm-charts …

Supporting template evaluation in ingress hosts

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/ci/label-annotations-values.yaml
charts/dex/templates/deployment.yaml
charts/dex/templates/servicemonitor.yaml
charts/dex/values.yaml

Signed-off-by: Jan-Otto Kröpke <joe@cloudeteer.de>
Added the ability to define custom annotations on deployment/pods
Tools like https://github.com/stakater/Reloader depends on that.

Supporting custom labels/annotations on deployment/pod

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/hpa.yaml

Use updated autoscaling API Version for HorizontalPodAutoscaler.
The `autoscaling/v2beta1` API version of HorizontalPodAutoscaler isn't served on K8s versions >=1.25. The Dex chart should support the newer version of the API, `autoscaling/v2` which is available on K8s versions >=1.23.

feat(charts/dex): use updated HorizontalPodAutoscaler API Version

---

charts/dex/Chart.yaml
charts/dex/README.md

Bump Dex to v2.37.0. The new version is out! 🚀

Bump Dex to v2.37.0

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/deployment.yaml
charts/dex/values.yaml

Especially when using GitOps approach to deploy DexIdP it makes not real sense to keep revisions of the deployments as those are actually kind of persisted inside the underlying SCM, which drives the deployment and its history.
It simply adds the possibility to configure the `revisionHistoryLimit` property of the `Deployment` resource template, but keeps the default to `10`.

Add spec.revisionHistoryLimit config possibility for Deployment resource

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/hpa.yaml

In chart version 0.14.3 (#111), the API Version of the Autoscaling object was updated to address an upstream API version deprecation in Kubernetes 1.25. However, the formatting under the `.spec.metrics[]` field changed which was not caught in testing. This would lead to the error below:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2.ResourceMetricSource]
```
This bug will break configuration running Kubernetes versions >= 1.25 that are using the …

fix(charts/dex): Templating error caused by #111

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/values.yaml

Add missing default values on ServiceMonitor.
In https://github.com/dexidp/helm-charts/pull/105 two new values, `.Values.serviceMonitor.honorLabels` and `.Values.serviceMonitor.path`, was introduced without any default values. If these values are not set by the user the value become `null` and installation in a k8s cluster fails.

fix: add missing defaults on servicemonitor

---

charts/dex/Chart.yaml
charts/dex/README.md

Bump Dex to v2.39.0. The new version is out! 🚀

Bump Dex to v2.39.0

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/NOTES.txt
charts/dex/templates/service.yaml
charts/dex/values.yaml

Add loadBalancerIP option to manually define an IP address when service type loadBalancer is defined.
The helm chart currently has the option to define a service type but if service type is set to loadBalancer then there is no option to define a loadBalancerIP. The service type loadBalancer with loadBalancerIP option exposes the dex service externally with a defined load balancer IP for those instances where a load balancer IP cannot be assigned dynamically.
Checklist

feat: Add .Values.service.loadBalancerIP option

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/_helpers.tpl
charts/dex/templates/deployment.yaml
charts/dex/templates/hpa.yaml
charts/dex/templates/ingress.yaml
charts/dex/templates/networkpolicy.yaml
charts/dex/templates/poddisruptionbudget.yaml
charts/dex/templates/rbac.yaml
charts/dex/templates/secret.yaml
charts/dex/templates/service.yaml
charts/dex/templates/serviceaccount.yaml
charts/dex/templates/servicemonitor.yaml
charts/dex/values.yaml

This PR adds the `namespace` to all resources, using the `Relase.Namespace` provided by Helm.
Fixes #120
As mentioned in #120 the Chart currently doesn't set the namespace on the resources, resulting in different behavior for `helm template` and `helm install` commands, as documented in https://github.com/helm/helm/issues/3553
The recommended solution by Helm is to set the namespace explicitly, as is done by a lot of other Charts (eg. cert-manager just to name one).

feat: Add release namespace to all resources

---

charts/dex/Chart.yaml
charts/dex/README.md
charts/dex/templates/deployment.yaml
charts/dex/values.yaml

- Replaced static values with tpl for image repository, tag, and digest to allow the parent chart’s values to be passed dynamically to subchart.
- Allow image pull using digest

feat(charts/dex): Use tpl for dynamic image values and add digest 

---

charts/dex/Chart.yaml
charts/dex/README.md

Updating dex to 2.44.0:
https://github.com/dexidp/dex/releases/tag/v2.44.0
There's a new dex version which we should make available via the helm chart.

chore: update Dex to 2.44.0
